name: Build and Install

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Define environment variables for the entire job
      FIREBASE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build:ts
        env:
          FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ env.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ env.FIREBASE_CLIENT_EMAIL }}
